package bean;
// Generated 21/05/2017 11:23:01 by Hibernate Tools 4.3.1


import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Horario generated by hbm2java
 */
@Entity
@Table(name="horario"
    ,catalog="outro145_victor_barber_db"
)
public class Horario  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    private Integer id;
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "SERVICO_FK") 
    private Servico servico;
    @Column(name="OBSERVACAO", length=65535)
    private String observacao;
    @Column(name="HORARIO_INICIO")
    private String horarioInicio;
    @Column(name="HORARIO_FIM")
    private String horarioFim;

    public Horario(Integer id, Servico servico, String observacao, String horarioInicio, String horarioFim) {
        this.id = id;
        this.servico = servico;
        this.observacao = observacao;
        this.horarioInicio = horarioInicio;
        this.horarioFim = horarioFim;
    }

    public Horario() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Servico getServico() {
        return servico;
    }

    public void setServico(Servico servico) {
        this.servico = servico;
    }

    public String getObservacao() {
        return observacao;
    }

    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }

    public String getHorarioInicio() {
        return horarioInicio;
    }

    public void setHorarioInicio(String horarioInicio) {
        this.horarioInicio = horarioInicio;
    }

    public String getHorarioFim() {
        return horarioFim;
    }

    public void setHorarioFim(String horarioFim) {
        this.horarioFim = horarioFim;
    }
}


