package bean;
// Generated 21/05/2017 11:23:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name="servico"
    ,catalog="outro145_victor_barber_db"
)
public class Servico  implements java.io.Serializable {


    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
     private Integer id;
    @Column(name="NOME", length=150)
     private String nome;
@Column(name="DURACAO_MINUTOS")
     private Integer duracaoMinutos;
@Column(name="PRECO", precision=22, scale=0)
     private Double preco;

    public Servico() {
    }

    public Servico(Integer id, String nome, Integer duracaoMinutos, Double preco) {
        this.id = id;
        this.nome = nome;
        this.duracaoMinutos = duracaoMinutos;
        this.preco = preco;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getDuracaoMinutos() {
        return duracaoMinutos;
    }

    public void setDuracaoMinutos(Integer duracaoMinutos) {
        this.duracaoMinutos = duracaoMinutos;
    }

    public Double getPreco() {
        return preco;
    }

    public void setPreco(Double preco) {
        this.preco = preco;
    }

    
    




}


