package bean;
// Generated 05/05/2017 15:52:32 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name="servico"
    ,catalog="victor_barber_db"
)
public class Servico  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Integer duracaoMinutos;
     private Double preco;

    public Servico() {
    }

    public Servico(String nome, Integer duracaoMinutos, Double preco) {
       this.nome = nome;
       this.duracaoMinutos = duracaoMinutos;
       this.preco = preco;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="NOME")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="DURACAO_MINUTOS")
    public Integer getDuracaoMinutos() {
        return this.duracaoMinutos;
    }
    
    public void setDuracaoMinutos(Integer duracaoMinutos) {
        this.duracaoMinutos = duracaoMinutos;
    }

    
    @Column(name="PRECO")
    public Double getPreco() {
        return this.preco;
    }
    
    public void setPreco(Double preco) {
        this.preco = preco;
    }




}


